#!/bin/bash
# Demo script for Speech Recognition App

echo "🎤 Speech Recognition App Demo"
echo "================================"
echo ""
echo "✅ Application successfully installed and configured!"
echo ""
echo "📋 Available Features:"
echo "   • Multiple API Support (Google, Deepgram, Sphinx)"
echo "   • Real-time speech recognition"
echo "   • Pause/Resume functionality"
echo "   • Save transcriptions to file"
echo "   • Multi-language support"
echo "   • Enhanced error handling"
echo ""
echo "🔧 Setup Instructions:"
echo ""
echo "1. For Google Speech-to-Text:"
echo "   export GOOGLE_APPLICATION_CREDENTIALS='/path/to/credentials.json'"
echo ""
echo "2. For Deepgram API:"
echo "   export DEEPGRAM_API_KEY='your-api-key'"
echo ""
echo "3. Run the application:"
echo "   cd /home/john-hika/Public/S_R_A"
echo "   ./venv/bin/python speech_recognition_app.py"
echo ""
echo "🎯 Runtime Commands:"
echo "   • 'pause' - Pause recognition"
echo "   • 'resume' - Resume recognition"
echo "   • 'stop' - Stop and show results"
echo "   • 'save' - Save transcription to file"
echo ""
echo "✨ The app is ready to use!"
echo "   - Sphinx (offline) works without API keys"
echo "   - Google & Deepgram require API setup for best accuracy"
